import Layout from '@layouts/Layout';
import Head from 'next/head';
import _ from 'lodash';
import { DataFilters } from '@components/DataFilters';
import { ActionButtons } from '@components/ActionButtons';
import { ModalRecogidas } from '@components/modals/ModalRecogidas';
import { RecogidasContextProvider } from '@context/recogidasContext';
import { ModalDespachos } from '@components/modals/ModalDespachos';
import { NextPage } from 'next';
import { MdFilterAlt, MdFilterAltOff } from 'react-icons/md';
import { useState } from 'react';
import CardLote from '@components/cards/CardLote';
import PrivateRoute from '@components/PrivateRoute';
import { useQuery } from '@apollo/client';
import { GET_FILTERED_COLLECTIONS } from 'graphql/client/collections';
import { Lot } from '@prisma/client';
import { TypeColumn } from '@inovua/reactdatagrid-community/types';
import ReactDataGrid from '@inovua/reactdatagrid-community';
import '@inovua/reactdatagrid-community/index.css';
import { GET_LOTS } from 'graphql/client/lots';
import { ExtendedCollection } from 'types';

const Home: NextPage = () => {
  const [showFilters, setShowFilters] = useState<boolean>(false);
  return (
    <PrivateRoute>
      <Layout>
        <>
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <meta
              name='viewport'
              content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <RecogidasContextProvider>
            <>
              <div className='flex h-full w-full flex-col gap-3 p-2 lg:p-10'>
                <div className='flex justify-center gap-2'>
                  <h1>Despachos y Recogidas</h1>
                  <button
                    onClick={() => setShowFilters(!showFilters)}
                    type='button'
                    className='icon'
                  >
                    {showFilters ? <MdFilterAltOff /> : <MdFilterAlt />}
                  </button>
                </div>
                <div className='flex flex-col items-center justify-center gap-3 lg:flex-row lg:justify-between'>
                  {showFilters && <DataFilters />}
                  <ActionButtons />
                </div>
                <TableDesktop />
                <MobileCards />
              </div>
              <ModalRecogidas />
              <ModalDespachos />
            </>
          </RecogidasContextProvider>
        </>
      </Layout>
    </PrivateRoute>
  );
};

const years = [2021, 2022, 2023];

const months = [
  { name: 'Enero', value: 0 },
  { name: 'Febrero', value: 1 },
  { name: 'Marzo', value: 2 },
  { name: 'Abril', value: 3 },
  { name: 'Mayo', value: 4 },
  { name: 'Junio', value: 5 },
  { name: 'Julio', value: 6 },
  { name: 'Agosto', value: 7 },
  { name: 'Septiembre', value: 8 },
  { name: 'Octubre', value: 9 },
  { name: 'Noviembre', value: 10 },
  { name: 'Diciembre', value: 11 },
];

const TableDesktop = () => {
  // const tableData = _.groupBy(data, 'Fecha');
  const [dateFilters, setDateFilters] = useState<{
    month: number;
    year: number;
  }>({ month: 4, year: 2023 });

  const { data, loading } = useQuery<{
    filterCollections: ExtendedCollection[];
  }>(GET_FILTERED_COLLECTIONS, {
    variables: {
      month: dateFilters.month,
      year: dateFilters.year,
    },
    fetchPolicy: 'cache-first',
  });

  const { data: lotData, loading: lotDataLoading } = useQuery<{ lots: Lot[] }>(
    GET_LOTS
  );

  if (loading || lotDataLoading) return <div>Loading...</div>;

  const lotColumns =
    lotData?.lots.map((lot) => ({
      name: lot.name,
      header: lot.name,
      defaultFlex: 1,
      headerProps: {
        style: {
          backgroundColor: '#3730A3',
          color: 'white',
        },
      },
    })) ?? [];

  const columns: TypeColumn[] = [
    {
      name: 'collectionDate',
      header: 'Fecha de recogida',
      defaultFlex: 1,
      headerProps: {
        style: {
          backgroundColor: '#3730A3',
          color: 'white',
        },
      },
    },
    ...lotColumns,
  ];

  const filterValues =
    lotData?.lots?.map((lot) => ({
      name: lot.name,
      operator: 'gte',
      type: 'number',
      value: '0',
    })) ?? [];

  const tableData = _.groupBy(data?.filterCollections, 'collectionDate');

  const transformedData = Object.keys(tableData).map((collectionDate) => {
    const lotData: { [key: string]: string | number } = {
      collectionDate,
    };

    tableData[collectionDate].forEach((collection) => {
      lotData[collection.lot.name] = collection.bunches;
    });

    return lotData;
  });

  return (
    <div className='flex h-full w-full flex-col items-center gap-2'>
      <div className='flex w-full justify-center gap-2'>
        <label>
          <span>Año</span>
          <select
            value={dateFilters.year.toString()}
            onChange={(e) =>
              setDateFilters((prev) => ({
                ...prev,
                year: parseInt(e.target.value),
              }))
            }
          >
            <option value='' disabled>
              Seleccionar Año
            </option>
            {years.map((year) => (
              <option key={`year_${year}`} value={year}>
                {year}
              </option>
            ))}
          </select>
        </label>
        <label>
          <span>Mes</span>
          <select
            value={dateFilters.month.toString()}
            onChange={(e) =>
              setDateFilters((prev) => ({
                ...prev,
                month: parseInt(e.target.value),
              }))
            }
          >
            <option value='' disabled>
              Seleccionar mes
            </option>
            {months.map((month) => (
              <option key={`month_${month.value}`} value={month.value}>
                {month.name}
              </option>
            ))}
          </select>
        </label>
      </div>
      <div className='hidden h-full w-full flex-col lg:flex'>
        <ReactDataGrid
          columns={columns}
          dataSource={transformedData}
          defaultFilterValue={filterValues}
          pagination
          pageSizes={[5, 10, 15, 20, 25, 31]}
        />
      </div>
    </div>
  );
};

const MobileCards = () => {
  const lotes = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  return (
    <div className='grid h-full grid-cols-2 gap-3 lg:hidden'>
      {lotes.map((lote) => (
        <CardLote key={`lote_${lote}`} name={lote.toString()} />
      ))}
    </div>
  );
};

export default Home;
